# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MindMine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MindMine

  target 'MindMineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MindMineUITests' do
    # Pods for testing
  end

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth’
end
